function [Detail_Appliance] = ApplianceSpec

% This is an average distribution from the Remodece database for each
% appliance for Norway mostly. This is an aggregated value from multiple
% measurments.

AppliancesList = {'WashMach';...
                  'DishWash';...
                  'Elec';...
                  'Kettle';...
                  'Oven';...
                  'MW';...
                  'Coffee';...
                  'Toas';...
                  'Waff';...
                  'Fridge';...
                  'Radio';... 
                  'Laptop';...
                  'Elecheat';...
                  'Shaver';...
                  'Hair';...
                  'Tele';...
                  'Stereo';...
                  'Iron';...
                  'Vacuum';...
                  'Charger';...
                  'Sauna'...
                  }';
              
[~,sheet_name] = xlsfinfo('Specificities_Appliances_Simulation.xlsx') ;

for k=1:numel(sheet_name)
  SheetNameExtract = sheet_name{k} ;
  if any(strcmp(SheetNameExtract,AppliancesList))
      [AppDistri,~,~] = xlsread('Specificities_Appliances_Simulation.xlsx',sheet_name{k}) ;
      Detail_Appliance.(SheetNameExtract) = array2table(AppDistri,'VariableNames',{'MaxUse','Temp','TimeUsage','Weekdistr','Weekdayweight','Weekdayacc','Delay','Power'}) ;
  end
end