function [RptgenML_CReport1] = buildfigloop_tutorial
%BUILDFIGLOOP_TUTORIAL
 
%  Auto-generated by MATLAB on 31-Oct-2014 16:46:14
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Description',...
['A report which demonstrates advanced component types:',sprintf('\n'),'',sprintf('\n'),'* Loops',sprintf('\n'),'* Property Tables',sprintf('\n'),'* Summary Tables'],...
'Stylesheet','html-!SingleClearTitleTocLot',...
'DirectoryType','pwd');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('Copyright_Date','1998',...
'Author','MathWorks',...
'Subtitle','A Tutorial',...
'Title','The Figure Loop');
rptgen_cfr_text1 = rptgen.cfr_text('Content',...
'The Figure Loop produces a report which documents multiple figure windows.  Each time the Figure Loop component runs, it reports on a different figure.');
set(rptgen_cfr_titlepage1,'AbstractComp',rptgen_cfr_text1);
rptgen_cfr_text2 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'LegalNoticeComp',rptgen_cfr_text2);
rptgen_cfr_image1 = rptgen.cfr_image('FileName','','MaxViewportSize',[7 9]);
set(rptgen_cfr_titlepage1,'ImageComp',rptgen_cfr_image1);
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Code for Creating Figures');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cml_eval
rptgen_cml_eval1 = rptgen.cml_eval('isInsertString',false,'isDiary',false,...
'isCatch',false,...
'EvalString',['% Create figures with a wide variety',sprintf('\n'),'% of Tag, Visible, and HandleVisibility',sprintf('\n'),'% properties.',sprintf('\n'),'',sprintf('\n'),'figloopfigures;']);
setParent(rptgen_cml_eval1,rptgen_cfr_section1);
 
% Create rptgen.crg_import_file
rptgen_crg_import_file1 = rptgen.crg_import_file('FileName',...
'figloopfigures.m','ImportType','code_highlighted');
setParent(rptgen_crg_import_file1,rptgen_cfr_section1);
 
% Create rptgen_hg.chg_summ_table
rptgen_hg_chg_summ_table1 = rptgen_hg.chg_summ_table('FilterEmptyColumns',...
true,'ColumnWidths',[3 2 1 1],...
'Properties',{'Name','Tag','Visible','HandleVisibility'},...
'Anchor',false);
setParent(rptgen_hg_chg_summ_table1,rptgen_cfr_section1);
 
% Create rptgen_hg.chg_fig_loop
rptgen_hg_chg_fig_loop1 = rptgen_hg.chg_fig_loop('TagList',...
{'peaks','membrane','app'},'LoopType','TAG');
set(rptgen_hg_chg_summ_table1,'LoopComp',rptgen_hg_chg_fig_loop1);
 
% Create rptgen.cfr_section
rptgen_cfr_section2 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Figures in Report');
setParent(rptgen_cfr_section2,RptgenML_CReport1);
 
% Create rptgen_hg.chg_fig_loop
rptgen_hg_chg_fig_loop2 = rptgen_hg.chg_fig_loop('TagList',...
{'app','membrane'},'LoopType','TAG','ObjectAnchor',true,...
'ObjectSection',true);
setParent(rptgen_hg_chg_fig_loop2,rptgen_cfr_section2);
 
% Create rptgen_hg.chg_fig_snap
rptgen_hg_chg_fig_snap1 = rptgen_hg.chg_fig_snap('PrintSize',[4 4],...
'isResizeFigure','manual',...
'MaxViewportSize',[7 9]);
setParent(rptgen_hg_chg_fig_snap1,rptgen_hg_chg_fig_loop2);
 
% Create rptgen_hg.chg_prop_table
rptgen_hg_chg_prop_table1 = rptgen_hg.chg_prop_table('ColWidths',...
[0.32823613086771 0.67176386913229],'SingleValueMode',true);
setParent(rptgen_hg_chg_prop_table1,rptgen_hg_chg_fig_loop2);
 
% Create rptgen.rpt_prop_cell
rptgen_rpt_prop_cell1 = rptgen.rpt_prop_cell('Render','N v',...
'Text','%<Name>');
addCell(rptgen_hg_chg_prop_table1,rptgen_rpt_prop_cell1);
 
% Create rptgen.rpt_prop_cell
rptgen_rpt_prop_cell2 = rptgen.rpt_prop_cell('Text','%<HandleVisibility>');
addCell(rptgen_hg_chg_prop_table1,rptgen_rpt_prop_cell2);
 
% Create rptgen.rpt_prop_cell
rptgen_rpt_prop_cell3 = rptgen.rpt_prop_cell('Text','%<Tag>');
addCell(rptgen_hg_chg_prop_table1,rptgen_rpt_prop_cell3);
 
% Create rptgen.rpt_prop_cell
rptgen_rpt_prop_cell4 = rptgen.rpt_prop_cell('Text','%<Visible>');
addCell(rptgen_hg_chg_prop_table1,rptgen_rpt_prop_cell4);
 
% Create rptgen.rpt_prop_cell
rptgen_rpt_prop_cell5 = rptgen.rpt_prop_cell('TitleMode',true);
set(rptgen_hg_chg_prop_table1,'TableTitle',rptgen_rpt_prop_cell5);
 
