function [RptgenML_CReport1] = buildReport_Gen
%BUILDREPORT_GEN
 
%  Auto-generated by MATLAB on 17-Aug-2018 09:33:47
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('isAutoSaveOnGenerate',true,...
'Format','dom-pdf-direct',...
'Stylesheet','default-rg-pdf',...
'isIncrementFilename',true);
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('AuthorMode','auto',...
'Title','House Details');
rptgen_cfr_text1 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'AbstractComp',rptgen_cfr_text1);
rptgen_cfr_text2 = rptgen.cfr_text;
set(rptgen_cfr_titlepage1,'LegalNoticeComp',rptgen_cfr_text2);
rptgen_cfr_image1 = rptgen.cfr_image('FileName',...
'E:\Work\Smart_Energy_Grid_and_House\Simulation\Smart Buidling Simulation\Version\Beta\MatLab model Beta\Input\GUI\Info_Simple_bw.png',...
'MaxViewportSize',[7 9]);
set(rptgen_cfr_titlepage1,'ImageComp',rptgen_cfr_image1);
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('StyleName','rgChapterTitle');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph('TitleType','specify');
rptgen_cfr_text3 = rptgen.cfr_text;
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text3);
setParent(rptgen_cfr_paragraph1,rptgen_cfr_section1);
 
% Create rptgen.cfr_text
rptgen_cfr_text4 = rptgen.cfr_text('Content',...
'We are trying to generate a report here');
setParent(rptgen_cfr_text4,rptgen_cfr_paragraph1);
 
