function BackEnd()

gui.Filter = figure('units','pixels',...
                 'toolbar','none',...
                 'menu','none',....
                 'name','Back-End',....
                 'NumberTitle','off',...
                 'Tag','AddFigure',...
                 'CloseRequestFcn',@closeRequest);
             

end

function closeRequest(src,~)
ButtonName = questdlg('Close window?', ...
                 'Close Check', ...
                 'Yes', 'No','No');
switch ButtonName
    case 'Yes'
        data.ValidAdd = 0;
        delete(src);
    case 'No'
        return
end
end %closeRequest