function [nbr_appliances, Series_App] = App_Nbr(varargin)
HouseTitle = varargin{1};
Input_Data = varargin{2};
nbr_applinces = [0, 0];
Series_App = [find(1==strcmp('WashMach',HouseTitle)),...
              find(1==strcmp('DishWash',HouseTitle)),...
              find(1==strcmp('Elec',HouseTitle)),...
              find(1==strcmp('Kettle',HouseTitle)),...
              find(1==strcmp('Oven',HouseTitle)),...
              find(1==strcmp('MW',HouseTitle)),...
              find(1==strcmp('Coffee',HouseTitle)),...
              find(1==strcmp('Toas',HouseTitle)),...
              find(1==strcmp('Waff',HouseTitle)),...
              find(1==strcmp('Fridge',HouseTitle)),...
              find(1==strcmp('Radio',HouseTitle)),...
              find(1==strcmp('Laptop',HouseTitle)),...
              find(1==strcmp('Elecheat',HouseTitle)),...
              find(1==strcmp('Shaver',HouseTitle)),...
              find(1==strcmp('Hair',HouseTitle)),...
              find(1==strcmp('Tele',HouseTitle)),...
              find(1==strcmp('Stereo',HouseTitle)),...
              find(1==strcmp('Iron',HouseTitle)),...
              find(1==strcmp('Vacuum',HouseTitle)),...
              find(1==strcmp('Charger',HouseTitle)),...
              find(1==strcmp('Sauna',HouseTitle));1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]';
AppClass = {'WashMach' 'DishWash' 'Elec' 'Kettle' 'Oven' 'MW' 'Coffee' 'Toas' 'Waff' 'Fridge' 'Radio' 'Laptop' 'Elecheat' 'Shaver' 'Hair' 'Tele' 'Stereo' 'Iron' 'Vacuum' 'Charger' 'Sauna'} ;      
for var_app = 1:21
    var_appn = Series_App(var_app,1); %[43,45,47,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,79,80]
    if ~sum(str2double(Input_Data.(AppClass{var_app}))) == 0
        for var_nbr = 1:sum(str2double(Input_Data.(AppClass{var_app})))
            nbr_applinces(size(nbr_applinces,1) + 1,1) = size(nbr_applinces,1);
            nbr_applinces(length(nbr_applinces),2) = find(Series_App == var_appn);
        end
    end
end
nbr_appliances = nbr_applinces(2:end,1:2);