%% Solar cells calculation
% Once the global solar radiation G(0) has been evaluated for the solar
% panels with a certain angles towards the sun, with a certain degree of 
% dirtiness and considering the reflectance of the glass coming from the 
% solar panel, the electricity generated by the solar panels must be 
% calculated. The methodology and equations used has been taken from 
% Luque (2004) and thus assumptions made come form the book. The
% methodology consists at calculating the voltage and current of one single
% cell of a solar module and then, depending on the solar irradiance, evaluating the power output of a series of cells. It is
% possible to outline real performance from technology available on the
% market. Technical description of several pv modules can be found in
% <http://www.photon.info/photon_site_db_solarmodule_en.photon?ActiveID=1242 Photon Magazine>
% database.
%% Starting function
% 
%%%
% the function used output the power produced from the solar module(s) as a 
% single double value. In order to succeed in calculating the power output
% of the solar modules, the function requires to have specification related
% to the environment in whic th panels have been installed: the global
% irradiance reaching the panels (_*Global_Irr*_), the sunrise time
% (_*Sunrise*_), the sunset time (_*Sunset*_), and the external temperature
% (_*Temperature*_). The default specifications defined in section 2.1.1 
% of the solar modules are passed if none have been defined.

function [Power] = PV_PanelsArray(Global_Irr, Sunrise, Sunset, Time_Sim, Input_Data, Temperature,Housenbr)

myiter = Time_Sim.myiter;
timehour = Time_Sim.timehour;
Tilt = str2double(Input_Data.Tilt) ;
MaxPowerPV = str2double(Input_Data.MaxPowerPV) ;
LengthPV = str2double(Input_Data.LengthPV) ;
WidthPV = str2double(Input_Data.WidthPV) ;
Nbrmodser = str2double(Input_Data.Nbrmodser) ;
Nbrmodpar = str2double(Input_Data.Nbrmodpar) ;
Aspect = str2double(Input_Data.Aspect) ;
Timeoffset = Time_Sim.Timeoffset;
Voc = str2double(Input_Data.Voc) ;
Isc = str2double(Input_Data.Isc) ;
NOCT = str2double(Input_Data.NOCT) ;
VTempCoff = str2double(Input_Data.VTempCoff) ;
% Voc
% if Input_Data{32}<= 0; Input_Data{32}= 36.3   ;Voc = Input_Data{32}; end
% Isc
% if Input_Data{33}<= 0; Input_Data{33}= 8.2   ; Isc = Input_Data{33}; end
% MaxPowerPV
% if Input_Data{34}<= 0; Input_Data{34}= 200   ; MaxPowerPV = Input_Data{34}; end
% LengthPV
% if Input_Data{35}<= 0; Input_Data{35}= 1657   ;LengthPV=Input_Data{35};  end
% WidthPV
% if Input_Data{36}<= 0; Input_Data{36}= 987   ; WidthPV=Input_Data{36}; end
% NOCT
% if Input_Data{37}<= 0; Input_Data{37}= 45   ; NOCT = Input_Data{37}; end
% VTempCoff
% if Input_Data{113}<= 0; Input_Data{113}= -0.0023   ; Vtempcoff = Input_Data{113}; end

%%% Calculation of the cell performances in general
%%% Thermal Voltage calculation
% The thermal voltage represents one of the characterisitcs of a
% semi-conductor and can be calculated using the Boltzmann constant K:
%%%
% $$V_{t}=\frac{KT}{q}$$
%%%
% Where _Vt_ is the thermal voltage [V], K is the Boltzmann constant equal
% to 1,3806505E-23 [J/K], q is the charge of an electron 1.602176565e-19
% [C], and T is the temperature [K].
Vt = 1.3806505e-23 * (273.15 + Temperature' ) / 1.602176565e-19;
%%% Open Ciruit voltage and short circuit current per cells
% The open circuit voltage is defined by the manufacturer and is available
% online for the entire module. Nevertheless, the method require to defin
% the Voc for each cells. In order to calculate it, the solar module
% dimensions are used as well as the standard dimension of a solar cell.
% Manufacturers are currently manufacturing solar cells of 156*156mm.
%%%
% $$V_{oc-cell}=\frac{V_{oc}}{\left \lfloor \frac{L}{156} \right \rfloor
% \times \left \lfloor \frac{W}{156} \right \rfloor}$$
%%%
% Where L is the lenght of the solar module [mm], W is the width of the
% solar module [mm], Voc is the open circuit voltage of the module [V]
%%%
% The nominal power delivered by a cell is calculated using the nominal power of the solar
% module declared by the manufacturer blanced by the size of the solar
% module.
%%%
% $$P_{m-cell}=\frac{P_{m}}{\left \lfloor \frac{L}{156} \right \rfloor
% \times \left \lfloor \frac{W}{156} \right \rfloor}$$
%%%
% Finally, the normalized voltage _voc_ is defined by the ratio between the
% open circuit voltage of a cell by the thermal voltage of the same cell.
%%%
% $$\mathit{v}_{oc}=\frac{V_{oc-cell}}{V_{t}}$$
Vocpercell = Voc / (fix(LengthPV/156) * fix(WidthPV/156));
Pmpercell  = MaxPowerPV / (fix(LengthPV/156) * fix(WidthPV/156));
voc        = Vocpercell ./ Vt;
%%% Fill Factor
% The fill factor _FF_ is one of the most important characteristic of a
% solar cell for representing its efficiency. I can be calculated from
% eq...
%%%
% $${FF}_{cell}=\frac{P_{m-cell}}{V_{oc-cell}\times I_{sc}}$$
FFpercell  = Pmpercell/(Vocpercell * Isc);
%%%
% Note that the short circuit current is the same for the whole panel or
% for the single solar cell as they are considered to be working in series.
%%% Series resistance
% Series resistance _rs_ is calculated using manufacturers data and is
% computed using the following equation:
%%%
% $${R}_{s}=\left ( 1-\frac{FF_{cell}}{FF_{0-cell}} \right
% )\frac{V_{oc-cell}}{I_{sc}}$$
%%%
% Where _FF0-cell_ is defined as,
%%%
% $${FF}_{0-cell}=\frac{v_{oc}-ln(v_{oc}+0.72)}{v_{oc}+1}$$
FF0percell = (voc - log(voc + 0.72)) ./ (voc+1);
Rs         = (1- FFpercell ./ FF0percell) * Vocpercell/ Isc;
% rs         = 1 - FFpercell / FF0percell;

% a          = voc + 1 - 2 * voc * rs;

%b          = a / (1 + a);

%Vm_Voc     = 1 - b / voc * ln(a)- rs * (1 - a^(-b));

%Im_Isc     = 1 - a^(-b);
%%% Cell Temperature
% In order to get the cell temperature, the Nominal Operating Cell
% Temperature (NOCT), the outside temperature, and the global irradiance
% coming on the solar panel is used. The general equation can be found as:
%%%
% $${T}_{cell}=T_{out}\frac{NOCT-20}{800}G(\beta ,\alpha )_{corr}$$
%%%
% Where _G_ is the global irradiance reaching the inclined surface found
% from Eq 55, NOCT is expressed in [C] and is a manufacturer data, 800 is
% constant of nominal solar radiation [W/m2] at which the cell has been
% tested.
Ct = (NOCT - 20) / 800;
Tc = Temperature' + Ct .* Global_Irr;
%%% Voltage and current at cell temperature
% In case the default value has been chosen from the form (_*Vtempcoff =
% -1*_), then the standard value for the voltage temperature coefficient
% is set by default equal to -2.3 mV/C. Nevertheless, this characteristics
% is often given by the manufacturer and is available on
% <http://www.photon.info/photon_site_db_solarmodule_en.photon?ActiveID=1242
% Photon Magazine>. Standard value of the voltage temperature coefficient
% is given in %/C and not straight in mV. Thus, s simple convervsion is
% made by taking the cell voltage _*Vocpercell*_.
%%%
% $$\frac{dV_{oc}}{dT_{c}}=V_{oc-cell}\frac{dV_{oc}}{100}$$
%%%
% thus the open circuit voltage for a certain temperature is evaluated using
% Eq ... (Tc from up there)
%%%
% $$ V_{oc}(T_{c})=V_{oc-cell}+(T_{c}-25)\frac{dV_{oc}}{dT_{c}}$$
%%%
% Similarly, the short circuit current of the solar cell varies only
% depending on the amount of irradiance received. The current variation is
% expressed by:
%%%
% $$I_{SC}(G)=I_{SC}\frac{G(\beta ,\alpha )_{corr}}{G_{nominal}}$$
%%%
% and,
%%%
% $$\mathit{v}_{oc}(G)=\frac{V_{oc}(T_{c})}{V_{t}}$$
%%%
% and the open circuit voltage of a cell is recalculated considering the
% thermal influence on its performance.
if ~(VTempCoff == -0.0023)
    VTempCoff = Vocpercell * VTempCoff / 100         ;
end
Vocpercell  = Vocpercell + (Tc - 25) * VTempCoff;
Isc        = Isc * Global_Irr / 1000;
voc        = Vocpercell ./ Vt;
%%% Power output
% It is thus possible to calculate the power output from the solar cell.
% Before being able to calculate the maximum power point operation _Pmp_,
% the normalised resistance _rs_ must be calculated from the series
% resistance calculated in Eq..._rs_ is null if either the open circuit
% voltage or the short circuit current is null.
%%%
% $$r_{s}=R_{s} \frac{I_{sc}(G)}{V_{oc}(T_{c})}$$

rsg                 = Rs ./ (Vocpercell ./ Isc)   ;
rsg(Vocpercell < 0) = 0                         ;   
rsg(Isc < 0)        = 0                         ;

% if or(Vocpercell < 0,Isc < 0)
%     rsg = 0;
% else
%     rsg = Rs / (Vocpercell / Isc);
% end
%%%
% The maximum voltage and current point operation, can thus be evaluated
% using the following equation:
%%%
% $$\frac{V_{M}}{V_{oc}(T_{c})}=1-\frac{b}{\mathit{v}_{oc}(G)}ln(a)-r_{s}(1-a^{-b})$$
%%%
% And,
%%%
% $$\frac{I_{M}}{I_{SC}(G)}=1-a^{-b}$$
%%%
% Where _a_ and _b_ are variables equal to,
%%%
% $$a=\mathit{v}_{oc}(G)+1-2\mathit{v}_{oc}(G)r_{s}$$
%%%
% And,
%%%
% $$b=\frac{a}{1+a}$$
a_atGeff = voc + 1 - 2 * voc .* rsg;
b_atGeff = a_atGeff ./ (1 + a_atGeff);
Vm_Voc_atGeff = 1- b_atGeff ./ voc .* log(a_atGeff) - rsg .* (1 - a_atGeff.^(-b_atGeff));
Im_Isc_atGeff = 1 - a_atGeff.^(-b_atGeff);
%%%
% The overall voltage is calculated from the voltage of a single solar
% cell. It requires to know the number of cells in the panel and as
% previously mentioned in Eq... uses the standard dimenions of a solar cell
% and the dimension of the module input in the function. Another variable
% is to highlight how many modules in series are in the system,
%%%
% $$V_{oc-system}=\left ( \left \lfloor \frac{L}{156} \right \rfloor\cdot \left \lfloor \frac{W}{156} \right \rfloor \right )\cdot n_{mod-ser}\cdot V_{oc}(T_{c})$$
%%%
% And,
%%%
% $$V_{M}=\frac{V_{M}}{V_{oc}(T_{c})}\cdot V_{oc-system}$$
%%%
% The maximum voltage point operation is thus deduced from Eq... 
Vocg_System = (fix(LengthPV/156) * fix(WidthPV/156)) * Nbrmodser * Vocpercell;
VM_atGeff   = Vm_Voc_atGeff .* Vocg_System;
%%%
% The maximum current point operation is
%%%
% $$I_{M}=\frac{I_{M}}{I_{SC}(G)}\cdot I_{SC}(G)\cdot
% max(1,n_{mod-par})$$
IM_atGeff   = Im_Isc_atGeff .* Isc * max(1,Nbrmodpar);
%%%
% The maximum power point operation _*Ppm*_ is thus simply calculated by
% multiplying the optimal voltage/current comnination
%%%
% $$P_{M}=\frac{V_{M}I_{M}}{1000}$$
%%%
% Where _PM_ is the maximum power output from the system [kW]. Further, the
% output power is corrected by the power consumed pby the system in case of
% a 1-axis or a 2-axis system that uses a control system and an electric
% motor to rotate the structure. A standard value of 35 W is being used as
% a standard power.
%%%
% $$P_{M}=\frac{V_{M}I_{M}}{1000}-P_{motor}$$
PM_atGeff   = (VM_atGeff .* IM_atGeff) / 1000;

motorpower = zeros(size(Sunrise,1),1) ;

if or(Tilt == -1, Aspect == -1)
    motorpower(Sunrise < Time_Sim.HourArray & Time_Sim.HourArray < Sunset) = 35 / 1000;
end





% if and(Sunrise < timehour,timehour < Sunset)
%     if or(Tilt == -1, Aspect == -1)
%         motorpower = 35 / 1000;
%     else
%         motorpower = 0;
%     end
% else
%     motorpower = 0;
% end

Power = PM_atGeff - motorpower;
    



