%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\jlouis\Dropbox\Smart Energy Grid and
%    House\Literature\Electricity in
%    Finland\KaikkiSiirtohinnat_Price_per_Company.xlsx Worksheet: Sheet2
%
% To extend the code for use with different selected data or a different strcat('Sheet',num2str(spsheet))
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/10/24 14:29:01
% KaikkiSiirtohinnatPriceperCompanyS1 = zeros(89,10,96);
dbstop if error
% clear all
MaxSheet = 96 ;
Company_Price_List = cell(90,11,MaxSheet);
for spsheet = 1:MaxSheet
    %% Import the data
    [~, ~, c] = xlsread('C:\Users\jlouis\Dropbox\Work\Smart House\Electricity in Finland\KaikkiSiirtohinnat_Price_per_Company.xlsx',strcat('Sheet',num2str(spsheet)),'D2:N91');
    Company_Price_List(:,:,spsheet) = c;
    Company_Price_List(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),Company_Price_List(:,:,spsheet))) = {''};
end
% for Col = 1:MaxSheet
%     for Row = 1:90
%         List_Name(Row,Col)=Company_Price_List(Row,1,Col);
%     end
% end
% RowCol=1; 
% for Col=1:MaxSheet
%     for Row = 1:90
%         List_Name2(RowCol,1)=Company_Price_List(Row,1,Col);RowCol = RowCol + 1;
%     end
% end